'use strict';
const fs=require('node:fs'),path=require('node:path'),vm=require('node:vm'),assert=require('node:assert/strict');
process.env.TZ='Asia/Taipei';
const R=path.resolve(__dirname,'..'),receiver=process.argv[2]||path.join(__dirname,'fixtures/receiver-vocab-sync.js'),report=[];
function store(){const m=new Map();return {getItem:k=>m.has(k)?m.get(k):null,setItem:(k,v)=>m.set(k,String(v)),removeItem:k=>m.delete(k),key:i=>[...m.keys()][i]??null,get length(){return m.size}}}
function makeContext(storage=store()){
 const noop=()=>{},ctx={console,Date,Math,JSON,Intl,Set,Map,Promise,performance:{now:()=>Date.now()},localStorage:storage,navigator:{},setTimeout:noop,clearTimeout:noop,setInterval:noop,clearInterval:noop,document:{readyState:'loading',visibilityState:'visible',addEventListener:noop,getElementById:()=>null,createElement:()=>({}),head:{appendChild:noop}},toast:noop,renderAll:noop,db:{tasks:[],logs:[]},save(){ctx.saved=JSON.stringify(ctx.db);return !ctx.failSave}};
 ctx.window=ctx;ctx.addEventListener=noop;ctx.getTask=id=>ctx.db.tasks.find(t=>t.id===id);
 ctx.periodForTask=t=>t?.level===4?ctx.periodForTask(ctx.getTask(t.parent)):t?.level===3?{start:t.start||'',due:t.due||''}:null;
 ctx.publishGoalEvent=e=>{const hub=JSON.parse(storage.getItem('GoalManagerToeicEventHubV2')||'{"events":[]}');if(!hub.events.some(x=>x.eventId===e.eventId))hub.events.unshift(e);storage.setItem('GoalManagerToeicEventHubV2',JSON.stringify(hub))};
 return vm.createContext(ctx);
}
function loadSender(c){vm.runInContext(fs.readFileSync(path.join(R,'vocab-goal-sync.js'),'utf8'),c);return c.ToeicVocabSync}
function loadReceiver(c){vm.runInContext(fs.readFileSync(receiver,'utf8'),c);return c.GoalManagerToeicSync}
function tasks(c){c.db.tasks=[{id:'g3',name:'語言能力準備',level:1},{id:'g3-1',level:2,parent:'g3'},
 {id:'g3-1-1',level:3,parent:'g3-1',start:'2026-09-07',due:'2026-09-27'},
 {id:'g3-1-1-1',name:'多益核心字彙',level:4,parent:'g3-1-1',weeklyMinutes:75},
 {id:'g3-1-1-2',name:'文法與句型基礎',level:4,parent:'g3-1-1',weeklyMinutes:75},
 {id:'g3-2',level:2,parent:'g3'}, {id:'g3-2-2',level:3,parent:'g3-2',start:'2026-09-28',due:'2026-10-25'},
 {id:'g3-2-2-1',name:'Part 5–6 文法與段落填空',level:4,parent:'g3-2-2'}, {id:'g3-2-2-2',name:'Part 7 閱讀理解',level:4,parent:'g3-2-2'},
 {id:'g3-3',level:2,parent:'g3'}, {id:'g3-3-1',level:3,parent:'g3-3',start:'2026-11-03',due:'2026-11-09'},
 {id:'g3-3-1-1',name:'字彙／聽力維持',level:4,parent:'g3-3-1'}, {id:'g3-3-1-2',name:'錯題快速複習',level:4,parent:'g3-3-1'}];}
function quiz(id='q1',date='2026-09-22',seconds=600){return {id,mode:'meaning',set:Array.from({length:10},(_,i)=>({id:'word'+i,word:'word'})),index:10,answers:Array.from({length:10},(_,i)=>({text:'word',ok:i<8,date,at:date+'T04:00:00Z'})),timing:{version:1,startedAt:date+'T03:50:00Z',days:{[date]:seconds*1000},legacyPartial:false},completedAt:date+'T04:00:00Z'}}
function send(c,q){return c.ToeicVocabSync.complete(q,()=>{}).record}
function test(name,fn){fn();report.push({name,status:'PASS'});console.log('PASS',name)}
const c=makeContext(),S=loadSender(c);tasks(c);const G=loadReceiver(c);
test('ten measured minutes produce one stable vocabulary event with 10 questions and 80 percent accuracy',()=>{const r=send(c,quiz());assert.equal(r.event.durationMinutes,10);assert.equal(r.event.accuracy,.8);assert.equal(r.event.questionsAnswered,10);assert.equal(r.event.correctAnswers,8);assert.equal(r.event.articlesCompleted,0);assert.equal(r.event.readingWpm,0)});
test('core vocabulary receives 100 percent of vocabulary minutes; grammar receives zero',()=>{G.syncOnce();assert.equal(c.db.logs.length,1);assert.equal(c.db.logs[0].taskId,'g3-1-1-1');assert.equal(c.db.logs[0].minutes,10);assert.equal(c.db.logs[0].sourceRoundQuestions,10);assert.equal(c.db.logs[0].sourceCorrect,8)});
test('duplicate completion and 100 repeated synchronizations do not add minutes or results',()=>{for(let i=0;i<100;i++){send(c,quiz());G.syncOnce()}assert.equal(c.db.logs.length,1);assert.equal(S.records().length,1)});
test('completion is immutable even if a stale tab supplies different time and answers',()=>{const altered=quiz();altered.timing.days['2026-09-22']=9900000;altered.answers[9].ok=true;assert.equal(send(c,altered).event.durationMinutes,10)});
test('new round IDs are independently counted',()=>{send(c,quiz('q2'));G.syncOnce();assert.equal(c.db.logs.reduce((n,l)=>n+l.minutes,0),20)});
test('subminute durations are not inflated to one minute',()=>{send(c,quiz('seconds','2026-09-22',12));G.syncOnce();assert.equal(c.db.logs.find(l=>l.sourceEventId==='toeic-vocab-seconds').minutes,.2)});
test('incomplete work cannot emit an event or mark itself complete',()=>{const q=quiz('partial');q.index=3;q.answers=q.answers.slice(0,3);delete q.completedAt;assert.throws(()=>send(c,q));assert.equal(q.completedAt,undefined);assert.equal(c.localStorage.getItem(S.keyFor('partial')),null)});
test('legacy completed vocabulary without timing preserves results and emits no invented minutes',()=>{const q=quiz('legacy');delete q.timing;const r=send(c,q);assert.equal(r.event,null);assert.equal(r.durationSeconds,0);assert.equal(r.total,10)});
test('vocabulary never enters the legacy hub read by an already-open old receiver',()=>{const x=makeContext();loadSender(x);const old={events:[{eventId:'old-article',activity:'toeic-news-training'}]};x.localStorage.setItem('GoalManagerToeicEventHubV2',JSON.stringify(old));send(x,quiz('isolated'));assert.deepEqual(JSON.parse(x.localStorage.getItem('GoalManagerToeicEventHubV2')),old);tasks(x);loadReceiver(x).syncOnce();assert(x.db.logs.some(l=>l.sourceEventId==='toeic-vocab-isolated'))});
test('durable vocabulary journal remains receivable after hub removal',()=>{const x=makeContext();loadSender(x);tasks(x);const g=loadReceiver(x);send(x,quiz('outbox'));x.localStorage.removeItem('GoalManagerToeicEventHubV2');g.syncOnce();assert.equal(x.db.logs[0].minutes,10)});
test('legacy stored progress and unrelated applications remain untouched',()=>{c.localStorage.setItem('sessions','OLD ARTICLE RESULTS');c.localStorage.setItem('ledger','OLD ACCOUNTING');send(c,quiz('safe'));G.syncOnce();assert.equal(c.localStorage.getItem('sessions'),'OLD ARTICLE RESULTS');assert.equal(c.localStorage.getItem('ledger'),'OLD ACCOUNTING')});
test('outside the vocabulary period is retained, not redirected to grammar or Part 7',()=>{const r=send(c,quiz('outside','2026-09-28'));G.syncOnce();assert(!c.db.logs.some(l=>l.sourceEventId===r.event.eventId));assert.equal(JSON.parse(c.localStorage.getItem(S.RECEIPT_PREFIX+r.event.eventId)).status,'deferred')});
test('inclusive start and due dates accept vocabulary activity',()=>{for(const d of ['2026-09-07','2026-09-27']){send(c,quiz(d,d));G.syncOnce();assert(c.db.logs.some(l=>l.sourceEventId==='toeic-vocab-'+d))}});
test('maintenance-period vocabulary goes only to vocabulary maintenance',()=>{send(c,quiz('maintenance','2026-11-03'));G.syncOnce();assert.equal(c.db.logs.find(l=>l.sourceEventId==='toeic-vocab-maintenance').taskId,'g3-3-1-1')});
test('missing or archived ancestor does not count toward an inactive goal',()=>{const x=makeContext();loadSender(x);tasks(x);const g=loadReceiver(x);x.getTask('g3').status='已封存';send(x,quiz('archive'));g.syncOnce();assert.equal(x.db.logs.length,0)});
test('midnight Taiwan dates are not treated as the preceding UTC date',()=>{const q=quiz('midnight','2026-09-07',15);q.completedAt='2026-09-06T16:01:00.000Z';send(c,q);G.syncOnce();assert.equal(c.db.logs.find(l=>l.sourceEventId==='toeic-vocab-midnight').sourceDate,'2026-09-07')});
test('multi-day round counts only the dates with matching active vocabulary actions',()=>{const q=quiz('days','2026-09-28',120);q.timing.days={'2026-09-27':60000,'2026-09-28':60000};send(c,q);G.syncOnce();const logs=c.db.logs.filter(l=>l.sourceEventId==='toeic-vocab-days');assert.equal(logs.length,1);assert.equal(logs[0].minutes,1);assert.equal(JSON.parse(c.localStorage.getItem(S.RECEIPT_PREFIX+'toeic-vocab-days')).status,'partial');G.syncOnce();assert.equal(c.db.logs.filter(l=>l.sourceEventId==='toeic-vocab-days').length,1)});
test('an explicit target still enforces the target period and never reassigns already counted dates',()=>{c.localStorage.setItem('GoalManagerToeicSync::vocabularyTargetV1','g3-2-2-1');G.syncOnce();assert.equal(c.db.logs.filter(l=>l.sourceEventId==='toeic-vocab-days').length,2);assert.equal(c.db.logs.find(l=>l.sourceEventId==='toeic-vocab-q1').taskId,'g3-1-1-1');c.localStorage.removeItem('GoalManagerToeicSync::vocabularyTargetV1')});
test('a save failure leaves goal logs and acknowledgements uncommitted; retry counts once',()=>{const x=makeContext();loadSender(x);tasks(x);const g=loadReceiver(x),r=send(x,quiz('save-fail'));x.failSave=true;assert.throws(()=>g.syncOnce());assert.equal(x.db.logs.length,0);assert.equal(x.localStorage.getItem('GoalManagerToeicSync::processed'),null);assert.equal(x.localStorage.getItem(S.RECEIPT_PREFIX+r.event.eventId),null);x.failSave=false;g.syncOnce();g.syncOnce();assert.equal(x.db.logs.length,1)});
test('removing a counted log does not make repeated sync resurrect the deleted input',()=>{const x=makeContext();loadSender(x);tasks(x);const g=loadReceiver(x);send(x,quiz('delete'));g.syncOnce();x.db.logs=[];g.syncOnce();assert.equal(x.db.logs.length,0)});
test('corrupt original hub is never overwritten by new vocabulary completion',()=>{const x=makeContext();loadSender(x);x.localStorage.setItem('GoalManagerToeicEventHubV2','broken-json');const result=x.ToeicVocabSync.complete(quiz('hub-bad'),()=>{});assert(result.published);assert.equal(x.localStorage.getItem('GoalManagerToeicEventHubV2'),'broken-json');assert(x.localStorage.getItem(S.keyFor('hub-bad')))});
test('corrupt completion record is retained rather than overwritten',()=>{const x=makeContext();loadSender(x);x.localStorage.setItem(S.keyFor('bad'),'broken');assert.throws(()=>send(x,quiz('bad')));assert.equal(x.localStorage.getItem(S.keyFor('bad')),'broken')});
test('writing the durable round can fail without producing a phantom goal event',()=>{const x=makeContext();loadSender(x);const old=x.localStorage.setItem;x.localStorage.setItem=(k,v)=>{if(k.startsWith(S.ROUND_PREFIX))throw Error('quota');old(k,v)};assert.throws(()=>send(x,quiz('quota')));assert.equal(x.localStorage.getItem('GoalManagerToeicEventHubV2'),null)});
test('processed marker history is not truncated at 600',()=>{const x=makeContext();loadSender(x);tasks(x);const g=loadReceiver(x);x.localStorage.setItem('GoalManagerToeicSync::processed',JSON.stringify(Array.from({length:650},(_,i)=>'old-'+i)));send(x,quiz('new'));g.syncOnce();assert(JSON.parse(x.localStorage.getItem('GoalManagerToeicSync::processed')).includes('old-0'))});
test('legacy complete-news allocation remains 55/45 and existing history is not rewritten',()=>{const x=makeContext();tasks(x);const g=loadReceiver(x),e={eventId:'old-news',endedAt:'2026-09-22T04:00:00Z',durationMinutes:20,questionsAnswered:9,correctAnswers:7,activity:'toeic-news-training'};x.localStorage.setItem('GoalManagerToeicEventHubV2',JSON.stringify({events:[e]}));g.syncOnce();assert.deepEqual(Array.from(x.db.logs.map(l=>l.minutes)).sort((a,b)=>a-b),[9,11]);const old=JSON.stringify(x.db.logs);g.syncOnce();assert.equal(JSON.stringify(x.db.logs),old)});
test('malformed daily durations are not accepted as actual study time',()=>{const x=makeContext();loadSender(x);tasks(x);const g=loadReceiver(x),r=send(x,quiz('malformed'));r.event.dailyDurations[0].durationSeconds=-30;x.localStorage.setItem(S.keyFor('malformed'),JSON.stringify(r));assert.equal(g.syncOnce().invalid,1);assert.equal(x.db.logs.length,0)});
function clockFixture(start=Date.parse('2026-09-22T10:00:00+08:00')){let n=start,m=0,vis=true;const q={id:'clock',answers:[]};const clock=S.createClock(q,()=>{},{wall:()=>n,mono:()=>m,visible:()=>vis});return {q,clock,advance(ms){n+=ms;m+=ms;clock.tick()},visible(v){vis=v;clock.visibility()},get now(){return n},get mono(){return m}}}
test('foreground timing accumulates actual seconds, independent of answer accuracy',()=>{const x=clockFixture();for(let i=0;i<60;i++)x.advance(1000);assert.equal(x.clock.seconds(),60)});
test('background time is excluded and timing resumes in foreground',()=>{const x=clockFixture();x.advance(1000);x.visible(false);for(let i=0;i<100;i++)x.advance(1000);x.visible(true);x.advance(1000);assert.equal(x.clock.seconds(),2)});
test('idle time pauses after 120 seconds and resumes on interaction',()=>{const x=clockFixture();for(let i=0;i<200;i++)x.advance(1000);assert.equal(x.clock.seconds(),120);x.clock.interact();x.advance(1000);assert.equal(x.clock.seconds(),121)});
test('process suspension is not counted as hours of training',()=>{const x=clockFixture();x.advance(1000);x.advance(3600000);x.clock.interact();x.advance(1000);assert.equal(x.clock.seconds(),2)});
test('reopening a persisted round does not include the time while it was closed',()=>{const x=clockFixture();x.advance(3000);x.clock.stop();const q=JSON.parse(JSON.stringify(x.q));let n=x.now+86400000;const clock=S.createClock(q,()=>{},{wall:()=>n,mono:()=>n,visible:()=>true});n+=2000;clock.tick();assert.equal(clock.seconds(),5)});
test('active study crossing local midnight is split into correct calendar days',()=>{const x=clockFixture(Date.parse('2026-09-27T23:59:55+08:00'));x.advance(10000);assert.equal(x.q.timing.days['2026-09-27'],5000);assert.equal(x.q.timing.days['2026-09-28'],5000)});
test('completed clocks cannot continue inflating study duration on repeated finish',()=>{const x=clockFixture();x.advance(3000);x.clock.stop();x.advance(5000);x.clock.interact();x.advance(5000);assert.equal(x.clock.seconds(),3)});
const summary={status:'PASS',checks:report.length,timezone:'Asia/Taipei',scope:'publisher and current receiver module with synthetic goal-store fixtures',tests:report};
const reportDir=process.env.TOEIC_TEST_REPORT_DIR||path.join(R,'qa');fs.mkdirSync(reportDir,{recursive:true});
fs.writeFileSync(path.join(reportDir,'vocab-sync-unit-report.json'),JSON.stringify(summary,null,2)+'\n');console.log('VOCAB_GOAL_SYNC_TESTS_PASS',report.length);
